language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install coverage codecov
install:
  -  pip install .
script:
  - coverage run -m unittest discover -s tests/
after_success:
  - codecov
